sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t thehill1111/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true thehill1111/docker-react npm run test
